# Generated by Django 4.2.1 on 2023-07-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uploaded_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
